% RAW Image Viewer
% Reads a 512x512 grayscale RAW image generated by the RISC-V image
% processing pipeline and displays it in MATLAB.

width  = 512;
height = 512;

fileID = fopen('output.raw', 'r');
img_data = fread(fileID, [width, height], 'uint8');
fclose(fileID);

% Convert from C/C++ row-major layout to MATLAB column-major layout
img = img_data';

figure;
imshow(img, []);
title('RISC-V Edge Detection Output');