name: RISC-V Canny CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install GoogleTest
      run: sudo apt-get update && sudo apt-get install -y libgtest-dev build-essential

    - name: Run Host Tests
      run: make test
